#!/bin/bash

set -e

usage() {
    echo "Usage: $0 FILE NEW_FILE FAKE_EXT_REVERSED REAL_EXT"
    echo "Example: $0 example.exe example fdp exe"
    exit 1
}

if [ "$#" -ne 4 ]; then
    usage
fi

FILE="$1"
NEW_FILE="$2"
FAKE_EXT_REVERSED="$3"
REAL_EXT="$4"

mv $FILE "$NEW_FILE$(echo -e '\xe2\x80\xae'${FAKE_EXT_REVERSED}.${REAL_EXT})"
